/**
 * THE RESUME CONTRACT
 * ===================
 * This is the single source of truth for what a resume looks like. Both the
 * editor UI and any external app (e.g. the referral tracker) must produce data
 * matching this shape. The on-screen template and the exported PDF render
 * exactly these fields — nothing more, nothing less.
 *
 * Design rule: the TEMPLATE is fixed. The CONTENT is variable. Adding a new
 * kind of section is a deliberate change to this file + the template, never an
 * ad-hoc thing an external caller can invent.
 */

/** Schema version. Bump when the shape changes in a breaking way. */
export const RESUME_SCHEMA_VERSION = 1 as const

export interface ContactInfo {
  /** Full name, shown as the resume headline. Required. */
  fullName: string
  /** e.g. "Senior Software Engineer" — shown under the name. Optional. */
  headline?: string
  email?: string
  phone?: string
  /** City, State / City, Country. */
  location?: string
  /** Bare domain or full URL, e.g. "linkedin.com/in/jane". */
  website?: string
  linkedin?: string
  github?: string
}

export interface ExperienceItem {
  company: string
  /** Job title / role. */
  title: string
  location?: string
  /** Free-form, e.g. "Jan 2022". */
  startDate?: string
  /** Free-form, e.g. "Present". */
  endDate?: string
  /** Bullet points describing impact. Rendered as a bulleted list. */
  highlights: string[]
}

export interface EducationItem {
  institution: string
  /** e.g. "B.S. Computer Science". */
  degree: string
  location?: string
  startDate?: string
  endDate?: string
  /** Optional extra line, e.g. "GPA 3.9 · Dean's List". */
  details?: string
}

export interface ProjectItem {
  name: string
  /** Optional link shown next to the name. */
  link?: string
  description?: string
  highlights: string[]
}

/** A named group of skills, e.g. { name: "Languages", items: ["Go", "TS"] }. */
export interface SkillGroup {
  name: string
  items: string[]
}

/**
 * The full resume document. `id`, `createdAt`, `updatedAt` are managed by the
 * app; an external caller may omit them and the app will fill them in.
 */
export interface Resume {
  schemaVersion: number
  /** Stable unique id. Generated by the app if omitted on ingest. */
  id: string
  /** Human label for this resume in the picker, e.g. "Backend roles — 2026". */
  label: string
  contact: ContactInfo
  /** Professional summary paragraph. Optional. */
  summary?: string
  experience: ExperienceItem[]
  education: EducationItem[]
  projects: ProjectItem[]
  skills: SkillGroup[]
  /** ISO timestamps, managed by the app. */
  createdAt: string
  updatedAt: string
}

/**
 * The subset an external app is expected to provide. Everything the app can
 * default is optional here. This is what the referral tracker builds.
 */
export type ResumeInput = {
  schemaVersion?: number
  id?: string
  label?: string
  contact: ContactInfo
  summary?: string
  experience?: ExperienceItem[]
  education?: EducationItem[]
  projects?: ProjectItem[]
  skills?: SkillGroup[]
}
